---
title: "git_00"
author: "Joel Calderin"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

"The Walrus and the Carpenter" By Lewis Carrol   

The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

"Acquainted with the Night" By Robert Frost

I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light.  
  
I have looked down the saddest city lane.  
I have passed by the watchman on his beat  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

In the realm of numbers, we seek to find the truth,  
In data's dance and patterns, we search for solid proof.  
Statistics, the magician, with its formulas and grace,  
Reveals the hidden stories, in every data's embrace.  

With measures and with graphs, we chart the unknown sea,  
A quest for understanding, in this vast complexity.  
Mean, median, and mode, they whisper secrets clear,  
Standard deviation's wisdom, dispelling doubt and fear.  

Hypotheses we form, and tests we boldly dare,  
To gauge the strength of evidence, to show what's truly there.  
In p-values and confidence intervals, we place our   trust,  
To separate mere chance from findings that are just.  
  
So in the world of numbers, where data's tales reside,  
Statistics stands as sentinel, by our inquisitive side.  
Unlocking mysteries, in numbers we confide,  
In this quest for knowledge, we'll let statistics be our guide.  
